-- ============================================================================
-- Snapshot do schema atual do banco Supabase (schema: public)
-- Gerado em: 2026-04-18
--
-- Este arquivo reflete o estado REAL do banco no Supabase no momento da
-- geracao, incluindo alteracoes feitas diretamente pelo painel do Supabase
-- que nao estavam refletidas nos scripts 001/002/003.
--
-- IMPORTANTE:
--   - Os scripts 001, 002 e 003 foram preservados como historico e NAO devem
--     mais ser usados como referencia do schema atual.
--   - Este script e idempotente (usa IF NOT EXISTS / CREATE OR REPLACE /
--     DROP POLICY IF EXISTS) e pode ser re-executado com seguranca em um
--     banco ja configurado.
--   - Apenas DDL (estrutura). Nao contem dados (INSERTs).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- EXTENSIONS
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- TABELA: public.clientes
-- Armazena perfis dos clientes / admins vinculados a auth.users.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.clientes (
  id          uuid        NOT NULL,
  nome        text        NOT NULL,
  email       text        NOT NULL,
  cnpj        text        NOT NULL,
  role        text        NOT NULL DEFAULT 'cliente_ingapan',
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  CONSTRAINT clientes_pkey       PRIMARY KEY (id),
  CONSTRAINT clientes_email_key  UNIQUE (email),
  CONSTRAINT clientes_cnpj_key   UNIQUE (cnpj),
  CONSTRAINT clientes_role_check CHECK (role IN ('cliente_ingapan', 'admin_ingapan')),
  CONSTRAINT clientes_id_fkey    FOREIGN KEY (id)
    REFERENCES auth.users (id) ON DELETE CASCADE
);

-- ============================================================================
-- TABELA: public.product_categoria
-- Categorias de produtos (chave estrangeira usada por public.products).
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.product_categoria (
  id        integer GENERATED BY DEFAULT AS IDENTITY,
  category  text    NOT NULL,
  CONSTRAINT product_categoria_pkey          PRIMARY KEY (id),
  CONSTRAINT product_categoria_category_key  UNIQUE (category)
);

-- ============================================================================
-- TABELA: public.products
-- Produtos do catalogo.
-- Observacao: a coluna "categoria" (varchar) permanece por compatibilidade,
-- mas o vinculo correto com a categoria e via "id_categoria" (FK).
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.products (
  id            bigint  GENERATED BY DEFAULT AS IDENTITY,
  nome          varchar,
  categoria     varchar,
  descricao     varchar,
  image_url     text,
  id_categoria  integer,
  CONSTRAINT products_pkey               PRIMARY KEY (id),
  CONSTRAINT products_id_categoria_fkey  FOREIGN KEY (id_categoria)
    REFERENCES public.product_categoria (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Indices auxiliares
CREATE INDEX IF NOT EXISTS products_categoria_idx     ON public.products (categoria);
CREATE INDEX IF NOT EXISTS products_id_categoria_idx  ON public.products (id_categoria);
CREATE INDEX IF NOT EXISTS products_nome_idx          ON public.products (nome);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Cria automaticamente um registro em public.clientes quando um novo usuario
-- e inserido em auth.users (executada via trigger on_auth_user_created).
CREATE OR REPLACE FUNCTION public.handle_new_cliente()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.clientes (id, nome, email, cnpj, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'nome', ''),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'cnpj', ''),
    'cliente_ingapan'
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$function$;

-- Retorna TRUE se o usuario informado (default auth.uid()) for admin_ingapan.
-- Usada pelas policies RLS para permitir acesso administrativo.
CREATE OR REPLACE FUNCTION public.is_admin_ingapan(target_user_id uuid DEFAULT auth.uid())
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.clientes c
    WHERE c.id = target_user_id
      AND lower(trim(c.role)) = 'admin_ingapan'
  );
$function$;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger em auth.users para popular public.clientes no signup.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_cliente();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- clientes: RLS habilitado
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

-- products: RLS habilitado
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- product_categoria: RLS NAO habilitado no banco atual.
-- (mantido desabilitado para refletir o estado real; se desejar habilitar,
--  descomente a linha abaixo e adicione as policies necessarias)
-- ALTER TABLE public.product_categoria ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- POLICIES: public.clientes
-- ----------------------------------------------------------------------------

-- Admins podem ler todos os clientes
DROP POLICY IF EXISTS admins_select_all ON public.clientes;
CREATE POLICY admins_select_all
  ON public.clientes
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

-- Admins podem atualizar qualquer cliente
DROP POLICY IF EXISTS admins_update_all ON public.clientes;
CREATE POLICY admins_update_all
  ON public.clientes
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

-- Cliente pode inserir apenas seu proprio registro (id = auth.uid())
DROP POLICY IF EXISTS clientes_insert_own ON public.clientes;
CREATE POLICY clientes_insert_own
  ON public.clientes
  FOR INSERT
  TO public
  WITH CHECK (auth.uid() = id);

-- Cliente pode ler o proprio registro
DROP POLICY IF EXISTS clientes_select_own ON public.clientes;
CREATE POLICY clientes_select_own
  ON public.clientes
  FOR SELECT
  TO public
  USING (auth.uid() = id);

-- Cliente pode atualizar o proprio registro
DROP POLICY IF EXISTS clientes_update_own ON public.clientes;
CREATE POLICY clientes_update_own
  ON public.clientes
  FOR UPDATE
  TO public
  USING (auth.uid() = id);

-- ----------------------------------------------------------------------------
-- POLICIES: public.products
-- ----------------------------------------------------------------------------

-- Leitura publica do catalogo (qualquer visitante)
DROP POLICY IF EXISTS products_public_select ON public.products;
CREATE POLICY products_public_select
  ON public.products
  FOR SELECT
  TO public
  USING (true);

-- Admin pode ler (redundante com a public_select, mas mantida conforme banco)
DROP POLICY IF EXISTS products_admin_select ON public.products;
CREATE POLICY products_admin_select
  ON public.products
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

-- Apenas admin pode inserir
DROP POLICY IF EXISTS products_admin_insert ON public.products;
CREATE POLICY products_admin_insert
  ON public.products
  FOR INSERT
  TO public
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

-- Apenas admin pode atualizar
DROP POLICY IF EXISTS products_admin_update ON public.products;
CREATE POLICY products_admin_update
  ON public.products
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

-- Apenas admin pode deletar
DROP POLICY IF EXISTS products_admin_delete ON public.products;
CREATE POLICY products_admin_delete
  ON public.products
  FOR DELETE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

-- ============================================================================
-- FIM DO SNAPSHOT
-- ============================================================================
