-- Tabela para controlar quais produtos aparecem no carrossel da home.
CREATE TABLE IF NOT EXISTS public.products_featured (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    bigint NOT NULL UNIQUE,
  display_order integer NOT NULL DEFAULT 1 CHECK (display_order > 0),
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT products_featured_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES public.products (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS products_featured_display_order_idx
  ON public.products_featured (display_order, id);

ALTER TABLE public.products_featured ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS products_featured_public_select ON public.products_featured;
CREATE POLICY products_featured_public_select
  ON public.products_featured
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS products_featured_admin_insert ON public.products_featured;
CREATE POLICY products_featured_admin_insert
  ON public.products_featured
  FOR INSERT
  TO public
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_featured_admin_update ON public.products_featured;
CREATE POLICY products_featured_admin_update
  ON public.products_featured
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_featured_admin_delete ON public.products_featured;
CREATE POLICY products_featured_admin_delete
  ON public.products_featured
  FOR DELETE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));
