-- Gestao de pedidos de clientes (WhatsApp checkout).

-- ============================================================================
-- TABELA: public.client_orders
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.client_orders (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     text NOT NULL,
  user_id        uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  customer_name  text NULL,
  customer_email text NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_orders_session_id_not_empty CHECK (length(btrim(session_id)) > 0)
);

CREATE INDEX IF NOT EXISTS client_orders_created_at_idx
  ON public.client_orders (created_at DESC);

CREATE INDEX IF NOT EXISTS client_orders_user_created_at_idx
  ON public.client_orders (user_id, created_at DESC);

-- ============================================================================
-- TABELA: public.client_order_items
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.client_order_items (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              bigint NOT NULL REFERENCES public.client_orders (id) ON DELETE CASCADE,
  product_id            bigint NULL REFERENCES public.products (id) ON DELETE SET NULL,
  product_name_snapshot text NOT NULL,
  quantity              integer NOT NULL CHECK (quantity > 0),
  created_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_order_items_unique_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS client_order_items_order_id_idx
  ON public.client_order_items (order_id);

-- ============================================================================
-- RLS
-- ============================================================================
ALTER TABLE public.client_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS client_orders_admin_select ON public.client_orders;
CREATE POLICY client_orders_admin_select
  ON public.client_orders
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS client_orders_user_select ON public.client_orders;
CREATE POLICY client_orders_user_select
  ON public.client_orders
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS client_order_items_admin_select ON public.client_order_items;
CREATE POLICY client_order_items_admin_select
  ON public.client_order_items
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS client_order_items_user_select ON public.client_order_items;
CREATE POLICY client_order_items_user_select
  ON public.client_order_items
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.client_orders co
      WHERE co.id = client_order_items.order_id
        AND co.user_id = auth.uid()
    )
  );

-- ============================================================================
-- FUNCTION: create_client_order
-- Um unico ponto de escrita para anon/authenticated, com validacao server-side.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.create_client_order(p_session_id text, p_items jsonb)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id uuid := auth.uid();
  v_order_id bigint;
  v_session_id text := btrim(COALESCE(p_session_id, ''));
  v_customer_name text;
  v_customer_email text;
  v_item_count integer;
  v_inserted_item_count integer;
BEGIN
  IF v_session_id = '' OR length(v_session_id) > 128 THEN
    RAISE EXCEPTION 'session_id invalido';
  END IF;

  IF jsonb_typeof(p_items) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'items invalidos';
  END IF;

  WITH normalized_items AS (
    SELECT
      (item ->> 'product_id')::bigint AS product_id,
      (item ->> 'quantity')::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item
  ),
  sanitized_items AS (
    SELECT
      ni.product_id,
      SUM(ni.quantity)::integer AS quantity
    FROM normalized_items ni
    WHERE ni.product_id IS NOT NULL
      AND ni.product_id > 0
      AND ni.quantity IS NOT NULL
      AND ni.quantity > 0
      AND ni.quantity <= 999
    GROUP BY ni.product_id
  )
  SELECT COUNT(*)
  INTO v_item_count
  FROM sanitized_items;

  IF v_item_count = 0 THEN
    RAISE EXCEPTION 'nenhum item valido';
  END IF;

  IF v_item_count > 100 THEN
    RAISE EXCEPTION 'limite de 100 itens distintos por pedido';
  END IF;

  IF v_user_id IS NOT NULL THEN
    SELECT c.nome, c.email
    INTO v_customer_name, v_customer_email
    FROM public.clientes c
    WHERE c.id = v_user_id;
  END IF;

  INSERT INTO public.client_orders (
    session_id,
    user_id,
    customer_name,
    customer_email
  )
  VALUES (
    v_session_id,
    v_user_id,
    v_customer_name,
    v_customer_email
  )
  RETURNING id INTO v_order_id;

  WITH normalized_items AS (
    SELECT
      (item ->> 'product_id')::bigint AS product_id,
      (item ->> 'quantity')::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item
  ),
  sanitized_items AS (
    SELECT
      ni.product_id,
      SUM(ni.quantity)::integer AS quantity
    FROM normalized_items ni
    WHERE ni.product_id IS NOT NULL
      AND ni.product_id > 0
      AND ni.quantity IS NOT NULL
      AND ni.quantity > 0
      AND ni.quantity <= 999
    GROUP BY ni.product_id
  ),
  validated_products AS (
    SELECT
      si.product_id,
      p.nome AS product_name_snapshot,
      si.quantity
    FROM sanitized_items si
    INNER JOIN public.products p
      ON p.id = si.product_id
  )
  INSERT INTO public.client_order_items (
    order_id,
    product_id,
    product_name_snapshot,
    quantity
  )
  SELECT
    v_order_id,
    vp.product_id,
    vp.product_name_snapshot,
    vp.quantity
  FROM validated_products vp;

  GET DIAGNOSTICS v_inserted_item_count = ROW_COUNT;

  IF v_inserted_item_count <> v_item_count THEN
    RAISE EXCEPTION 'um ou mais produtos informados sao invalidos';
  END IF;

  RETURN v_order_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.create_client_order(text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_client_order(text, jsonb)
  TO anon, authenticated, service_role;

