-- ============================================================================
-- Snapshot do schema atual do banco Supabase (schema: public)
-- Gerado em: 2026-04-19
--
-- Este arquivo consolida os objetos usados pela aplicacao, incluindo:
-- - clientes / products / product_categoria
-- - products_featured
-- - product_stats
-- - product_sales_stats
-- - client_orders / client_order_items
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- TABELAS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.clientes (
  id          uuid        NOT NULL,
  nome        text        NOT NULL,
  email       text        NOT NULL,
  cnpj        text        NOT NULL,
  role        text        NOT NULL DEFAULT 'cliente_ingapan',
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  CONSTRAINT clientes_pkey       PRIMARY KEY (id),
  CONSTRAINT clientes_email_key  UNIQUE (email),
  CONSTRAINT clientes_cnpj_key   UNIQUE (cnpj),
  CONSTRAINT clientes_role_check CHECK (role IN ('cliente_ingapan', 'admin_ingapan')),
  CONSTRAINT clientes_id_fkey    FOREIGN KEY (id)
    REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_categoria (
  id        integer GENERATED BY DEFAULT AS IDENTITY,
  category  text    NOT NULL,
  CONSTRAINT product_categoria_pkey          PRIMARY KEY (id),
  CONSTRAINT product_categoria_category_key  UNIQUE (category)
);

CREATE TABLE IF NOT EXISTS public.products (
  id            bigint  GENERATED BY DEFAULT AS IDENTITY,
  nome          varchar,
  categoria     varchar,
  descricao     varchar,
  image_url     text,
  id_categoria  integer,
  CONSTRAINT products_pkey               PRIMARY KEY (id),
  CONSTRAINT products_id_categoria_fkey  FOREIGN KEY (id_categoria)
    REFERENCES public.product_categoria (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS products_categoria_idx     ON public.products (categoria);
CREATE INDEX IF NOT EXISTS products_id_categoria_idx  ON public.products (id_categoria);
CREATE INDEX IF NOT EXISTS products_nome_idx          ON public.products (nome);

CREATE TABLE IF NOT EXISTS public.products_featured (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    bigint NOT NULL UNIQUE,
  display_order integer NOT NULL DEFAULT 1 CHECK (display_order > 0),
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT products_featured_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES public.products (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS products_featured_display_order_idx
  ON public.products_featured (display_order, id);

CREATE TABLE IF NOT EXISTS public.product_stats (
  product_id  bigint PRIMARY KEY,
  views_count bigint NOT NULL DEFAULT 0,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_stats_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES public.products (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_sales_stats (
  product_id    bigint PRIMARY KEY
    REFERENCES public.products (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  orders_count  bigint NOT NULL DEFAULT 0 CHECK (orders_count >= 0),
  units_sold    bigint NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS product_sales_stats_units_sold_desc_idx
  ON public.product_sales_stats (units_sold DESC);
CREATE INDEX IF NOT EXISTS product_sales_stats_orders_count_desc_idx
  ON public.product_sales_stats (orders_count DESC);

CREATE TABLE IF NOT EXISTS public.client_orders (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     text NOT NULL,
  user_id        uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  customer_name  text NULL,
  customer_email text NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_orders_session_id_not_empty CHECK (length(btrim(session_id)) > 0)
);

CREATE INDEX IF NOT EXISTS client_orders_created_at_idx
  ON public.client_orders (created_at DESC);
CREATE INDEX IF NOT EXISTS client_orders_user_created_at_idx
  ON public.client_orders (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.client_order_items (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              bigint NOT NULL REFERENCES public.client_orders (id) ON DELETE CASCADE,
  product_id            bigint NULL REFERENCES public.products (id) ON DELETE SET NULL,
  product_name_snapshot text NOT NULL,
  quantity              integer NOT NULL CHECK (quantity > 0),
  created_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_order_items_unique_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS client_order_items_order_id_idx
  ON public.client_order_items (order_id);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_cliente()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.clientes (id, nome, email, cnpj, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'nome', ''),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'cnpj', ''),
    'cliente_ingapan'
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin_ingapan(target_user_id uuid DEFAULT auth.uid())
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.clientes c
    WHERE c.id = target_user_id
      AND lower(trim(c.role)) = 'admin_ingapan'
  );
$function$;

CREATE OR REPLACE FUNCTION public.increment_product_view(target_product_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF target_product_id IS NULL OR target_product_id <= 0 THEN
    RAISE EXCEPTION 'target_product_id invalido';
  END IF;

  INSERT INTO public.product_stats (product_id, views_count, updated_at)
  VALUES (target_product_id, 1, now())
  ON CONFLICT (product_id)
  DO UPDATE
  SET
    views_count = public.product_stats.views_count + 1,
    updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_products_featured_limit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  featured_count integer;
BEGIN
  SELECT COUNT(*) INTO featured_count FROM public.products_featured;
  IF featured_count >= 10 THEN
    RAISE EXCEPTION 'Limite de 10 produtos em destaque atingido.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_client_order(p_session_id text, p_items jsonb)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id uuid := auth.uid();
  v_order_id bigint;
  v_session_id text := btrim(COALESCE(p_session_id, ''));
  v_customer_name text;
  v_customer_email text;
  v_item_count integer;
  v_inserted_item_count integer;
BEGIN
  IF v_session_id = '' OR length(v_session_id) > 128 THEN
    RAISE EXCEPTION 'session_id invalido';
  END IF;

  IF jsonb_typeof(p_items) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'items invalidos';
  END IF;

  WITH normalized_items AS (
    SELECT
      (item ->> 'product_id')::bigint AS product_id,
      (item ->> 'quantity')::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item
  ),
  sanitized_items AS (
    SELECT
      ni.product_id,
      SUM(ni.quantity)::integer AS quantity
    FROM normalized_items ni
    WHERE ni.product_id IS NOT NULL
      AND ni.product_id > 0
      AND ni.quantity IS NOT NULL
      AND ni.quantity > 0
      AND ni.quantity <= 999
    GROUP BY ni.product_id
  )
  SELECT COUNT(*)
  INTO v_item_count
  FROM sanitized_items;

  IF v_item_count = 0 THEN
    RAISE EXCEPTION 'nenhum item valido';
  END IF;

  IF v_item_count > 100 THEN
    RAISE EXCEPTION 'limite de 100 itens distintos por pedido';
  END IF;

  IF v_user_id IS NOT NULL THEN
    SELECT c.nome, c.email
    INTO v_customer_name, v_customer_email
    FROM public.clientes c
    WHERE c.id = v_user_id;
  END IF;

  INSERT INTO public.client_orders (
    session_id,
    user_id,
    customer_name,
    customer_email
  )
  VALUES (
    v_session_id,
    v_user_id,
    v_customer_name,
    v_customer_email
  )
  RETURNING id INTO v_order_id;

  WITH normalized_items AS (
    SELECT
      (item ->> 'product_id')::bigint AS product_id,
      (item ->> 'quantity')::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item
  ),
  sanitized_items AS (
    SELECT
      ni.product_id,
      SUM(ni.quantity)::integer AS quantity
    FROM normalized_items ni
    WHERE ni.product_id IS NOT NULL
      AND ni.product_id > 0
      AND ni.quantity IS NOT NULL
      AND ni.quantity > 0
      AND ni.quantity <= 999
    GROUP BY ni.product_id
  ),
  validated_products AS (
    SELECT
      si.product_id,
      p.nome AS product_name_snapshot,
      si.quantity
    FROM sanitized_items si
    INNER JOIN public.products p
      ON p.id = si.product_id
  )
  INSERT INTO public.client_order_items (
    order_id,
    product_id,
    product_name_snapshot,
    quantity
  )
  SELECT
    v_order_id,
    vp.product_id,
    vp.product_name_snapshot,
    vp.quantity
  FROM validated_products vp;

  GET DIAGNOSTICS v_inserted_item_count = ROW_COUNT;

  IF v_inserted_item_count <> v_item_count THEN
    RAISE EXCEPTION 'um ou mais produtos informados sao invalidos';
  END IF;

  RETURN v_order_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.apply_product_sales_stats_delta(
  p_product_id bigint,
  p_orders_delta integer,
  p_units_delta integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF p_product_id IS NULL OR p_product_id <= 0 THEN
    RETURN;
  END IF;

  IF p_orders_delta = 0 AND p_units_delta = 0 THEN
    RETURN;
  END IF;

  INSERT INTO public.product_sales_stats (product_id, orders_count, units_sold, updated_at)
  VALUES (
    p_product_id,
    GREATEST(p_orders_delta, 0)::bigint,
    GREATEST(p_units_delta, 0)::bigint,
    now()
  )
  ON CONFLICT (product_id)
  DO UPDATE
  SET
    orders_count = GREATEST(0, public.product_sales_stats.orders_count + p_orders_delta),
    units_sold = GREATEST(0, public.product_sales_stats.units_sold + p_units_delta),
    updated_at = now();

  DELETE FROM public.product_sales_stats
  WHERE product_id = p_product_id
    AND orders_count = 0
    AND units_sold = 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_product_sales_stats_from_order_items()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.apply_product_sales_stats_delta(NEW.product_id, 1, NEW.quantity);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD.product_id IS NOT NULL AND NEW.product_id IS NOT NULL AND OLD.product_id = NEW.product_id THEN
      PERFORM public.apply_product_sales_stats_delta(NEW.product_id, 0, NEW.quantity - OLD.quantity);
      RETURN NEW;
    END IF;

    PERFORM public.apply_product_sales_stats_delta(OLD.product_id, -1, -OLD.quantity);
    PERFORM public.apply_product_sales_stats_delta(NEW.product_id, 1, NEW.quantity);
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    PERFORM public.apply_product_sales_stats_delta(OLD.product_id, -1, -OLD.quantity);
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$function$;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_cliente();

DROP TRIGGER IF EXISTS products_featured_limit_trigger ON public.products_featured;
CREATE TRIGGER products_featured_limit_trigger
BEFORE INSERT ON public.products_featured
FOR EACH ROW
EXECUTE FUNCTION public.enforce_products_featured_limit();

DROP TRIGGER IF EXISTS client_order_items_sales_stats_sync ON public.client_order_items;
CREATE TRIGGER client_order_items_sales_stats_sync
AFTER INSERT OR UPDATE OR DELETE ON public.client_order_items
FOR EACH ROW
EXECUTE FUNCTION public.sync_product_sales_stats_from_order_items();

-- ============================================================================
-- BACKFILL
-- ============================================================================

INSERT INTO public.product_sales_stats (product_id, orders_count, units_sold, updated_at)
SELECT
  coi.product_id,
  COUNT(*)::bigint AS orders_count,
  SUM(coi.quantity)::bigint AS units_sold,
  now()
FROM public.client_order_items coi
WHERE coi.product_id IS NOT NULL
GROUP BY coi.product_id
ON CONFLICT (product_id)
DO UPDATE
SET
  orders_count = EXCLUDED.orders_count,
  units_sold = EXCLUDED.units_sold,
  updated_at = now();

-- ============================================================================
-- RLS E POLICIES
-- ============================================================================

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products_featured ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_sales_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admins_select_all ON public.clientes;
CREATE POLICY admins_select_all
  ON public.clientes
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS admins_update_all ON public.clientes;
CREATE POLICY admins_update_all
  ON public.clientes
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS clientes_insert_own ON public.clientes;
CREATE POLICY clientes_insert_own
  ON public.clientes
  FOR INSERT
  TO public
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS clientes_select_own ON public.clientes;
CREATE POLICY clientes_select_own
  ON public.clientes
  FOR SELECT
  TO public
  USING (auth.uid() = id);

DROP POLICY IF EXISTS clientes_update_own ON public.clientes;
CREATE POLICY clientes_update_own
  ON public.clientes
  FOR UPDATE
  TO public
  USING (auth.uid() = id);

DROP POLICY IF EXISTS products_public_select ON public.products;
CREATE POLICY products_public_select
  ON public.products
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS products_admin_select ON public.products;
CREATE POLICY products_admin_select
  ON public.products
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_admin_insert ON public.products;
CREATE POLICY products_admin_insert
  ON public.products
  FOR INSERT
  TO public
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_admin_update ON public.products;
CREATE POLICY products_admin_update
  ON public.products
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_admin_delete ON public.products;
CREATE POLICY products_admin_delete
  ON public.products
  FOR DELETE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_featured_public_select ON public.products_featured;
CREATE POLICY products_featured_public_select
  ON public.products_featured
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS products_featured_admin_insert ON public.products_featured;
CREATE POLICY products_featured_admin_insert
  ON public.products_featured
  FOR INSERT
  TO public
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_featured_admin_update ON public.products_featured;
CREATE POLICY products_featured_admin_update
  ON public.products_featured
  FOR UPDATE
  TO public
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS products_featured_admin_delete ON public.products_featured;
CREATE POLICY products_featured_admin_delete
  ON public.products_featured
  FOR DELETE
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS product_stats_public_select ON public.product_stats;
CREATE POLICY product_stats_public_select
  ON public.product_stats
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS product_sales_stats_admin_select ON public.product_sales_stats;
CREATE POLICY product_sales_stats_admin_select
  ON public.product_sales_stats
  FOR SELECT
  TO authenticated
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS client_orders_admin_select ON public.client_orders;
CREATE POLICY client_orders_admin_select
  ON public.client_orders
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS client_orders_user_select ON public.client_orders;
CREATE POLICY client_orders_user_select
  ON public.client_orders
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS client_order_items_admin_select ON public.client_order_items;
CREATE POLICY client_order_items_admin_select
  ON public.client_order_items
  FOR SELECT
  TO public
  USING (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS client_order_items_user_select ON public.client_order_items;
CREATE POLICY client_order_items_user_select
  ON public.client_order_items
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.client_orders co
      WHERE co.id = client_order_items.order_id
        AND co.user_id = auth.uid()
    )
  );

-- ============================================================================
-- PERMISSIONS
-- ============================================================================

DROP POLICY IF EXISTS product_stats_public_insert ON public.product_stats;
DROP POLICY IF EXISTS product_stats_public_update ON public.product_stats;
DROP POLICY IF EXISTS product_stats_public_delete ON public.product_stats;
DROP POLICY IF EXISTS product_sales_stats_public_insert ON public.product_sales_stats;
DROP POLICY IF EXISTS product_sales_stats_public_update ON public.product_sales_stats;
DROP POLICY IF EXISTS product_sales_stats_public_delete ON public.product_sales_stats;

REVOKE INSERT, UPDATE, DELETE ON TABLE public.product_stats FROM anon, authenticated;
GRANT SELECT ON TABLE public.product_stats TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.product_sales_stats FROM anon, authenticated;
GRANT SELECT ON TABLE public.product_sales_stats TO authenticated;

REVOKE ALL ON FUNCTION public.increment_product_view(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_product_view(bigint)
  TO anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.apply_product_sales_stats_delta(bigint, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_product_sales_stats_delta(bigint, integer, integer)
  TO service_role;

REVOKE ALL ON FUNCTION public.sync_product_sales_stats_from_order_items() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.sync_product_sales_stats_from_order_items()
  TO service_role;

REVOKE ALL ON FUNCTION public.create_client_order(text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_client_order(text, jsonb)
  TO anon, authenticated, service_role;

