-- ============================================================================
-- Migration: cria a tabela public.product_subcategory
--
-- Segue o mesmo molde de public.product_categoria:
--   - id (integer, identity, PK)
--   - subcategoria (text, NOT NULL, UNIQUE)
--
-- Tambem adiciona a FK public.products.id_subcategoria -> product_subcategory.id,
-- no mesmo padrao usado por products.id_categoria -> product_categoria.id.
--
-- Este script e idempotente (IF NOT EXISTS / DROP ... IF EXISTS) e pode ser
-- re-executado com seguranca em um banco ja configurado.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: public.product_subcategory
-- Subcategorias de produtos (chave estrangeira usada por public.products).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_subcategory (
  id           integer GENERATED BY DEFAULT AS IDENTITY,
  subcategoria text    NOT NULL,
  CONSTRAINT product_subcategory_pkey             PRIMARY KEY (id),
  CONSTRAINT product_subcategory_subcategoria_key UNIQUE (subcategoria)
);

-- ----------------------------------------------------------------------------
-- FK em public.products: vinculo com a subcategoria via "id_subcategoria".
-- Segue o mesmo padrao de "id_categoria" (ON UPDATE CASCADE / ON DELETE RESTRICT).
-- ----------------------------------------------------------------------------
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS id_subcategoria integer;

ALTER TABLE public.products
  DROP CONSTRAINT IF EXISTS products_id_subcategoria_fkey;

ALTER TABLE public.products
  ADD CONSTRAINT products_id_subcategoria_fkey
    FOREIGN KEY (id_subcategoria)
    REFERENCES public.product_subcategory (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Indice auxiliar para consultas/joins por subcategoria.
CREATE INDEX IF NOT EXISTS products_id_subcategoria_idx
  ON public.products (id_subcategoria);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
--
-- Alinha as tabelas de apoio ao mesmo modelo de public.products:
--   - Leitura publica (qualquer visitante pode listar categorias/subcategorias)
--   - Escrita (INSERT/UPDATE/DELETE) restrita a admins via is_admin_ingapan()
--
-- Ate entao public.product_categoria estava sem RLS habilitado; aqui
-- padronizamos ambas as tabelas. Idempotente via DROP POLICY IF EXISTS.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- RLS: public.product_categoria
-- ----------------------------------------------------------------------------
ALTER TABLE public.product_categoria ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS product_categoria_public_select ON public.product_categoria;
CREATE POLICY product_categoria_public_select
  ON public.product_categoria
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS product_categoria_admin_insert ON public.product_categoria;
CREATE POLICY product_categoria_admin_insert
  ON public.product_categoria
  FOR INSERT
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS product_categoria_admin_update ON public.product_categoria;
CREATE POLICY product_categoria_admin_update
  ON public.product_categoria
  FOR UPDATE
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS product_categoria_admin_delete ON public.product_categoria;
CREATE POLICY product_categoria_admin_delete
  ON public.product_categoria
  FOR DELETE
  USING (public.is_admin_ingapan(auth.uid()));

-- ----------------------------------------------------------------------------
-- RLS: public.product_subcategory
-- ----------------------------------------------------------------------------
ALTER TABLE public.product_subcategory ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS product_subcategory_public_select ON public.product_subcategory;
CREATE POLICY product_subcategory_public_select
  ON public.product_subcategory
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS product_subcategory_admin_insert ON public.product_subcategory;
CREATE POLICY product_subcategory_admin_insert
  ON public.product_subcategory
  FOR INSERT
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS product_subcategory_admin_update ON public.product_subcategory;
CREATE POLICY product_subcategory_admin_update
  ON public.product_subcategory
  FOR UPDATE
  USING (public.is_admin_ingapan(auth.uid()))
  WITH CHECK (public.is_admin_ingapan(auth.uid()));

DROP POLICY IF EXISTS product_subcategory_admin_delete ON public.product_subcategory;
CREATE POLICY product_subcategory_admin_delete
  ON public.product_subcategory
  FOR DELETE
  USING (public.is_admin_ingapan(auth.uid()));

-- ============================================================================
-- FIM DA MIGRATION
-- ============================================================================
